FROM golang:1.23-alpine AS builder
ENV GOTOOLCHAIN=auto

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/scheduler ./cmd/scheduler

FROM alpine:latest

RUN apk --no-cache add ca-certificates

COPY --from=builder /bin/scheduler /bin/scheduler

CMD ["/bin/scheduler"]
