FROM golang:1.23-alpine AS builder
ENV GOTOOLCHAIN=auto

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/slackbot ./cmd/slackbot

FROM alpine:latest

RUN apk --no-cache add ca-certificates

COPY --from=builder /bin/slackbot /bin/slackbot

CMD ["/bin/slackbot"]
